version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %p"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    level: DEBUG
    filename: logs/logging.log
    mode: "w"
    encoding: utf-8
    delay: True
root:
  level: DEBUG
  handlers: [file, console]
  propagate: yes
